<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divpassContainer</name>
   <tag></tag>
   <elementGuidId>e98d2c87-ace4-44e6-bdb0-ac6cf919a21c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='passContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>044caa04-0926-4f6c-98b5-986f160c9056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6luy _55r1 _1kbt</value>
      <webElementGuid>7874df61-26c6-41aa-8092-6d12c7edc37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passContainer</value>
      <webElementGuid>cf579faf-fbb4-4f61-a0a8-2f4f3a64ec1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passContainer&quot;)</value>
      <webElementGuid>979d3cc4-b70c-4d8b-a78c-88403aa7b42a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='passContainer']</value>
      <webElementGuid>58531561-efeb-49a2-b33d-e164e28a0e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_Ug']/div/div[2]/div</value>
      <webElementGuid>9c3b9c32-88f8-4356-8eb4-854cac106da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div</value>
      <webElementGuid>af39038d-5b5b-4dea-8a82-3d5f11dce5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'passContainer']</value>
      <webElementGuid>d2d26f31-5741-46c2-b9f3-9987791cec99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
